### ISSUE TITLE
ImportError: cannot import name 'Config' from 'mmcv'

### ISSUE THREAD

**Issue by Qusever** [PurdueDigitalTwin/REDFormer#1]
Could you kindly share the details of your environment installation, includes:
• Torch version:
• CUDA compiler version:
• MMDetection version:
• MMDetection3d version:
• MMCV version:
• MMEngine version or mmcv_runner version:
• Python version:
• Operating system platform:

**Comment by cancui19** [comment]
Thank you for your interest! Below are the details of my environment installation:

1. Torch version: 1.9.1
2. CUDA compiler version: CUDA 11.1
3.  MMDetection version: 2.28.2
4. MMDetection3d version: 1.0.0rc6
5. MMCV version: 1.6.2
6. MMEngine version or mmcv_runner version: N/A
7. Python version: 3.8
8. Operating system platform: Ubuntu 20.04
