### ISSUE TITLE
mmdet version incompatible

### ISSUE THREAD

**Issue by RuanBispo** [PurdueDigitalTwin/REDFormer#2]
mmcv version is incompatible if it is less than 2.0 but this way, the code doesn't works because only mmcv<2.0 has the config lib. What were the versions used?
![image](https://github.com/PurdueDigitalTwin/REDFormer/assets/61762635/871e173d-4bd1-42ba-9651-98f9e20619d9)

![image](https://github.com/PurdueDigitalTwin/REDFormer/assets/61762635/fbf1ffab-1c52-4ebb-aa50-38dc48649b75)

Thank you in advance!

Question: Versions for  mmcv-full, mmdet and mmsegmentation

**Comment by RuanBispo** [comment]
Could you send me your env file? (.yml) or upload to the repository?

`conda env export > my_conda_env.yml`

**Comment by cancui19** [comment]
Thanks for your interests.  Below are the versions for the packages you mentioned.
      - mmcv-full==1.6.2
      - mmdet==2.28.2
      - mmsegmentation==0.30.0

**Comment by RuanBispo** [comment]
Thank you for the answer! Could you send me the mmdetection3d version? or upload your modified version. I think that the current version has a new module named mmengine, but this is not true for mmcv<2.0.0, so if I install the mmdetection3d from the source it is not compatible with your code.

![image](https://github.com/PurdueDigitalTwin/REDFormer/assets/61762635/4b558517-97a1-421a-bdd5-7afc551450ae)

**Comment by RuanBispo** [comment]
cudatoolkit=11.0 only supports pytorch <1.7.1 and mmdetection3d requires pytorch > 1.8, I think

**Comment by cancui19** [comment]
Hello! The version of mmdet3d that I utilized was 1.0.0rc6. Additionally, I have uploaded my environment file in the 'conda_env' folder. To address the issue you mentioned, you might need to switch to the 1.0 branch during the installation of the mmdetection3d library. You can also refer to this [page](https://github.com/open-mmlab/mmdetection3d/blob/1.0/docs/en/getting_started.md) for detailed instructions on how to install the mmdet3d library.

**Comment by RuanBispo** [comment]
thank you! This worked for me, only one more observation, I had a problema with numba, but I installed your numpy version and it worked! 
numpy==1.23.5
