### ISSUE TITLE
Modify samples_per_gpu=2

### ISSUE THREAD

**Issue by luffydo** [PurdueDigitalTwin/REDFormer#3]
hi, I would like to ask if it is possible to change the ‘samples_per_gpu=2’ of the train code, but an error was reported after the modification：REDFormer/projects/mmdet3d_plugin/redformer/dense_heads/redformer_head.py，line 83"assert hidden.shape == (width * length, self.embedding_dim)"

**Comment by cancui19** [comment]
Thanks for your interest in our project, unfortunately, our current codes do not support a single GPU with multi-batch sizes.
